fn main() {
    #[cfg(windows)]
    windows::build!(
        Windows::Win32::Foundation::{
            CloseHandle,
            HANDLE,
            INVALID_HANDLE_VALUE,
            BOOL,
            PWSTR,
        },
        Windows::Win32::System::WindowsProgramming::{
            INFINITE,
        },
        Windows::Win32::System::Pipes::{
            CreatePipe,
        },
        Windows::Win32::System::Threading::{
            DeleteProcThreadAttributeList,
            PROCESS_CREATION_FLAGS,
            STARTUPINFOW,
            PROCESS_INFORMATION,
            STARTUPINFOW_FLAGS,
            LPPROC_THREAD_ATTRIBUTE_LIST,
            CreateProcessW,
            InitializeProcThreadAttributeList,
            UpdateProcThreadAttribute,
            WaitForSingleObject,
            GetExitCodeProcess,
            STARTUPINFOEXW,
        },
        Windows::Win32::System::Console::{
            GetStdHandle,
            ClosePseudoConsole,
            CreatePseudoConsole,
            GetConsoleMode,
            SetConsoleMode,
            COORD,
            CONSOLE_SCREEN_BUFFER_INFO,
            GetConsoleScreenBufferInfo,
            HPCON,
        },
        Windows::Win32::Storage::FileSystem::{
            WriteFile, ReadFile, CreateFileW,
        },
    );
}
